### ISSUE TITLE
what does SerializableParcelable means

### ISSUE THREAD

**Issue by jackuhan** [bunnyblue/SerializableParcelableGenerator#3]
it looks like Parcelable,what's the relationship between SerializableParcelable and Serializable.
这个看起来完成了Parcelable的序列化，难道同时兼容Serializable的序列化？可以本地存储？

**Comment by bunnyblue** [comment]
Parcelable没法持久化，Serializable这个慢很多，折中了下 采取了Parcelable接口实现，不兼容Serializable
